#!/usr/bin/env python

import sys
import subprocess

if len(sys.argv) < 3:
    print "command line: png_tile rows cols file1.png file2.png ..."
    print "   rows = number of horizontal copies"
    print "   cols = number of vertical copies"
    print "   file1.png to fileN.png = files to tile"
    sys.exit(1)

rows = int(sys.argv[1])
cols = int(sys.argv[2])

for file in sys.argv[3:]:
    target = file.replace('.png','.tiled.png')
    print "Processing %s:\n\tTiling vertically" % file
    command = ['convert'] +  [file]*rows  + ['-append'] + [target]
    subprocess.call(command)
    print "\tTiling horizontally"
    command = ['convert'] + [target]*cols + ['+append'] + [target]
    subprocess.call(command)