#!/usr/bin/env python
#
# make_png_grb
#    .png to .grb GUI wrapper
#
# Neil Gershenfeld
# CBA MIT 11/23/12
#
# (c) Massachusetts Institute of Technology 2012
# Permission granted for experimental and personal use;
# license for commercial sale available from MIT.
#
# imports
#
import wx,sys
from fab_set import fab_frame
from panel_control import control_panel
from panel_png import png_panel
from panel_png_grb import png_grb_panel
#
# command line
#
print "command line: make_png_grb [input_file [size]]"
print "   input_file = input .png file (optional)"
print "   size = image panel size (optional)"
#
# start wx
#
app = wx.App()
#
# add panels to frame
#
frame = fab_frame("make_png_grb",sys.argv)
frame.control_panel = control_panel(frame)
frame.sizer.Add(frame.control_panel,(0,0),span=(1,2),flag=wx.ALIGN_CENTER_HORIZONTAL)
frame.grb_panel = png_grb_panel(frame)
frame.sizer.Add(frame.grb_panel,(1,1))
frame.png_panel = png_panel(frame)
frame.sizer.Add(frame.png_panel,(1,0))
#
# set defaults
#
#frame.set_png_grb()
#
# fit and show frame
#
frame.Fit()
frame.Show()
#
# start mainloop
#
app.MainLoop()
