#!/usr/bin/env python
#
# make_svg_uni
#    .svg to .uni GUI wrapper
#
# Neil Gershenfeld
# CBA MIT 7/19/11
#
# (c) Massachusetts Institute of Technology 2011
# Permission granted for experimental and personal use;
# license for commercial sale available from MIT.
#
# imports
#
import wx,sys
from fab_set import fab_frame
from panel_control import control_panel
from panel_svg import svg_panel
from panel_svg_path import svg_path_panel
from panel_path_uni import path_uni_panel
#
# command line
#
print "command line: make_svg_uni [input_file [size]]"
print "   input_file = input .svg file (optional)"
print "   size = image panel size (optional)"
#
# start wx
#
app = wx.App()
#
# add panels to frame
#
frame = fab_frame("make_svg_camm",sys.argv)
frame.control_panel = control_panel(frame)
frame.sizer.Add(frame.control_panel,(0,0),span=(1,4),flag=wx.ALIGN_CENTER_HORIZONTAL)
frame.svg_panel = svg_panel(frame)
frame.sizer.Add(frame.svg_panel,(1,0))
frame.path_panel = svg_path_panel(frame)
frame.sizer.Add(frame.path_panel,(1,1))
frame.uni_panel = path_uni_panel(frame)
frame.sizer.Add(frame.uni_panel,(1,2))
#
# defaults
#
frame.set_svg_uni()
#
# fit and show frame
#
frame.Fit()
frame.Show()
#
# start mainloop
#
app.MainLoop()
