#!/usr/bin/env python
#
# make_cad_eps
#    .cad to .eps GUI wrapper
#
# Neil Gershenfeld 7/4/13
# (c) Massachusetts Institute of Technology 2013
#
# This work may be reproduced, modified, distributed,
# performed, and displayed for any purpose, but must
# acknowledge the fab modules project. Copyright is
# retained and must be preserved. The work is provided
# as is; no warranty is provided, and users accept all 
# liability.
#
# imports
#
import wx,sys
from fab_set import fab_frame
from panel_control import control_panel
from panel_cad import cad_panel
from panel_cad_png import cad_png_panel
from panel_png_path import png_path_panel
from panel_path_eps import path_eps_panel
#
# command line
#
print "command line: make_cad_eps [input_file [size]]"
print "   input_file = input .cad file (optional)"
print "   size = image panel size (optional)"
#
# start wx
#
app = wx.App()
#
# add panels to frame
#
frame = fab_frame("make_cad_eps",sys.argv)
frame.control_panel = control_panel(frame)
frame.sizer.Add(frame.control_panel,(0,0),span=(1,4),flag=wx.ALIGN_CENTER_HORIZONTAL)
frame.cad_panel = cad_panel(frame)
frame.sizer.Add(frame.cad_panel,(1,0))
frame.cad_png_panel = cad_png_panel(frame)
frame.sizer.Add(frame.cad_png_panel,(1,1))
frame.png_path_panel = png_path_panel(frame)
frame.sizer.Add(frame.png_path_panel,(1,2))
frame.eps_panel = path_eps_panel(frame)
frame.sizer.Add(frame.eps_panel,(1,3))
#
# defaults
#
frame.set_cad_eps()
#
# fit and show frame
#
frame.Fit()
frame.Show()
#
# start mainloop
#
app.MainLoop()
