#!/usr/bin/env python
#
# make_png_eps_halftone
#    .png to .eps halftone GUI wrapper
#
# Neil Gershenfeld 7/4/13
# (c) Massachusetts Institute of Technology 2013
#
# This work may be reproduced, modified, distributed,
# performed, and displayed for any purpose, but must
# acknowledge the fab modules project. Copyright is
# retained and must be preserved. The work is provided
# as is; no warranty is provided, and users accept all 
# liability.
#
# imports
#
import wx,sys
from fab_set import fab_frame
from panel_control import control_panel
from panel_png import png_panel
from panel_png_path_halftone import png_path_halftone_panel
from panel_path_eps import path_eps_panel
#
# command line
#
print "command line: make_png_eps_halftone [input_file [size]]"
print "   input_file = input .png file (optional)"
print "   size = image panel size (optional)"
#
# start wx
#
app = wx.App()
#
# add panels to frame
#
frame = fab_frame("make_png_eps_halftone",sys.argv)
frame.control_panel = control_panel(frame)
frame.sizer.Add(frame.control_panel,(0,0),span=(1,3),flag=wx.ALIGN_CENTER_HORIZONTAL)
frame.eps_panel = path_eps_panel(frame)
frame.sizer.Add(frame.eps_panel,(1,2))
frame.path_panel = png_path_halftone_panel(frame)
frame.sizer.Add(frame.path_panel,(1,1))
frame.png_panel = png_panel(frame)
frame.sizer.Add(frame.png_panel,(1,0))
#
# defaults
#
#frame.set_png_eps_halftone()
#
# fit and show frame
#
frame.Fit()
frame.Show()
#
# start mainloop
#
app.MainLoop()
