#!/usr/bin/env python
#
# make_math_ord
#    .math to .ord GUI wrapper
#
# Neil Gershenfeld
# CBA MIT 4/25/12
#
# (c) Massachusetts Institute of Technology 2012
# Permission granted for experimental and personal use;
# license for commercial sale available from MIT.
#
# imports
#
import wx,sys
from fab_set import fab_frame
from panel_control import control_panel
from panel_math import math_panel
from panel_math_png import math_png_panel
from panel_png_path import png_path_panel
from panel_path_ord import path_ord_panel
#
# command line
#
print "command line: make_math_ord [input_file [size]]"
print "   input_file = input .math file (optional)"
print "   size = image panel size (optional)"
#
# start wx
#
app = wx.App()
#
# add panels to frame
#
frame = fab_frame("make_math_ord",sys.argv)
frame.control_panel = control_panel(frame)
frame.sizer.Add(frame.control_panel,(0,0),span=(1,4),flag=wx.ALIGN_CENTER_HORIZONTAL)
frame.math_panel = math_panel(frame)
frame.sizer.Add(frame.math_panel,(1,0))
frame.png_panel = math_png_panel(frame)
frame.sizer.Add(frame.png_panel,(1,1))
frame.path_panel = png_path_panel(frame)
frame.sizer.Add(frame.path_panel,(1,2))
frame.ord_panel = path_ord_panel(frame)
frame.sizer.Add(frame.ord_panel,(1,3))
#
# defaults
#
frame.set_math_ord()
#
# fit and show frame
#
frame.Fit()
frame.Show()
#
# start mainloop
#
app.MainLoop()
