#!/usr/bin/env python
#
# make_cad_drl
#    .cad to .drl GUI wrapper
#
# Neil Gershenfeld
# CBA MIT 11/25/12
#
# (c) Massachusetts Institute of Technology 2012
# Permission granted for experimental and personal use;
# license for commercial sale available from MIT.
#
# imports
#
import wx,sys
from fab_set import fab_frame
from panel_control import control_panel
from panel_cad import cad_panel
from panel_cad_png import cad_png_panel
from panel_png_drl import png_drl_panel
#
# command line
#
print "command line: make_cad_drl [input_file [size]]"
print "   input_file = input .cad file (optional)"
print "   size = image panel size (optional)"
#
# start wx
#
app = wx.App()
#
# add panels to frame
#
frame = fab_frame("make_cad_drl",sys.argv)
frame.control_panel = control_panel(frame)
frame.sizer.Add(frame.control_panel,(0,0),span=(1,3),flag=wx.ALIGN_CENTER_HORIZONTAL)
frame.cad_panel = cad_panel(frame)
frame.sizer.Add(frame.cad_panel,(1,0))
frame.png_panel = cad_png_panel(frame)
frame.sizer.Add(frame.png_panel,(1,1))
frame.drl_panel = png_drl_panel(frame)
frame.sizer.Add(frame.drl_panel,(1,2))
#
# defaults
#
#frame.set_cad_drl()
#
# fit and show frame
#
frame.Fit()
frame.Show()
#
# start mainloop
#
app.MainLoop()
